post http://localhost:5000/v1/api/salchipapa
content-type: application/json

{
    "orden": "55",
    "nombre": "Salchipapa Mixta",
    "precio": "4.00",
    "descripcion": "La salchipapa contiene doble porcion de papas"
}

###
patch http://localhost:5000/v1/api/salchipapa/61218ab61d3579292c8660b2
content-type: application/json

{
    "orden": "48",
    "nombre": "Salchipapa Mixta",
    "precio": "4.00",
    "descripcion": "La salchipapa contiene doble porcion de papas"
}

###
get http://localhost:5000/v1/api/salchipapa

###
get http://localhost:5000/v1/api/salchipapa/61218ab61d3579292c8660b2

###
delete http://localhost:5000/v1/api/salchipapa/61218ab61d3579292c8660b2